### ISSUE TITLE
Fail when using installed software

### ISSUE THREAD

**Issue by hhx037** [hakyimlab/MetaXcan#102]
Hi,

though everything seems to be working fine when running the various software from MetaXcan/software, it's not the case when attempting to run the installed version (after using the setup script). Only SPrediXcan works after installation, here are the error messages for the others:

```
PrediXcan.py --help
Traceback (most recent call last):
  File "/data2/home/hhx037/python3/bin/PrediXcan.py", line 4, in <module>
    __import__('pkg_resources').run_script('MetaXcan==0.7.5', 'PrediXcan.py')
  File "/data2/home/hhx037/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/data2/home/hhx037/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1471, in run_script
    exec(script_code, namespace, namespace)
  File "/data2/home/hhx037/python3/lib/python3.6/site-packages/MetaXcan-0.7.5-py3.6.egg/EGG-INFO/scripts/PrediXcan.py", line 8, in <module>
ModuleNotFoundError: No module named 'Predict'
```

```
MulTiXcan.py --help
Traceback (most recent call last):
  File "/data2/home/hhx037/python3/bin/MulTiXcan.py", line 4, in <module>
    __import__('pkg_resources').run_script('MetaXcan==0.7.5', 'MulTiXcan.py')
  File "/data2/home/hhx037/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/data2/home/hhx037/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1471, in run_script
    exec(script_code, namespace, namespace)
  File "/data2/home/hhx037/python3/lib/python3.6/site-packages/MetaXcan-0.7.5-py3.6.egg/EGG-INFO/scripts/MulTiXcan.py", line 13, in <module>
ModuleNotFoundError: No module named 'metax.predixcan'
```

```
SMulTiXcan.py --help
Traceback (most recent call last):
  File "/data2/home/hhx037/python3/bin/SMulTiXcan.py", line 4, in <module>
    __import__('pkg_resources').run_script('MetaXcan==0.7.5', 'SMulTiXcan.py')
  File "/data2/home/hhx037/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/data2/home/hhx037/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1471, in run_script
    exec(script_code, namespace, namespace)
  File "/data2/home/hhx037/python3/lib/python3.6/site-packages/MetaXcan-0.7.5-py3.6.egg/EGG-INFO/scripts/SMulTiXcan.py", line 11, in <module>
ModuleNotFoundError: No module named 'metax.cross_model'
```

Any way I can fix this or you need to alter the setup script?

Cheers,

Steph

**Comment by Heroico** [comment]
Hi Steph,

Thank you for reporting this. I'm not sure what is going on, I'll investigate.
Are you installing to your system's python installation?
Are you using any environment management tool like pyenv or conda?
What's your OS?

Thanks in advance,

Alvaro

**Comment by hhx037** [comment]
Hi Alvaro,

I'm indeed using pyenv to manage my environment on the cluster, and the cluster is running on CentOS 7.7.1908

Thanks,

Steph

**Comment by weiminlee1** [comment]
Hi,
I also met the same bug after using conda to manage my environment on linux (Red Hat 4.8.5-28).

(imlabtools) [stu@master software]$ PrediXcan.py --help
Traceback (most recent call last):
  File "/public/home/stu/anaconda3/envs/imlabtools/bin/PrediXcan.py", line 4, in <module>
    __import__('pkg_resources').run_script('MetaXcan==0.7.5', 'PrediXcan.py')
  File "/public/home/stu/anaconda3/envs/imlabtools/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/public/home/stu/anaconda3/envs/imlabtools/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/public/home/stu/anaconda3/envs/imlabtools/lib/python3.7/site-packages/MetaXcan-0.7.5-py3.7.egg/EGG-INFO/scripts/PrediXcan.py", line 8, in <module>
ModuleNotFoundError: No module named 'Predict'



All best,

Weimin

**Comment by weiminlee1** [comment]
Hi, 

 I maybe found the reason for bug  about "ModuleNotFoundError: No module named 'Predict'", when i checked the PrediXcan.py script in my folder.

The script missed one line in the beginning.
The script worked after I added "#! /usr/bin/env python"

All best,

Weimin

**Comment by hhx037** [comment]
Hi Weimin,

Thanks for looking into this. I'm still getting the same error I'm afraid.
This is my PrediXcan.py file at the moment:

```
#! /usr/bin/env python
#! /data2/home/hhx037/python3/bin/python
# EASY-INSTALL-SCRIPT: 'MetaXcan==0.7.5','PrediXcan.py'
__requires__ = 'MetaXcan==0.7.5'
__import__('pkg_resources').run_script('MetaXcan==0.7.5', 'PrediXcan.py')
```

Cheers,

Steph

**Comment by weiminlee1** [comment]
> Hi Weimin,
> 
> Thanks for looking into this. I'm still getting the same error I'm afraid.
> This is my PrediXcan.py file at the moment:
> 
> ```
> #! /usr/bin/env python
> #! /data2/home/hhx037/python3/bin/python
> # EASY-INSTALL-SCRIPT: 'MetaXcan==0.7.5','PrediXcan.py'
> __requires__ = 'MetaXcan==0.7.5'
> __import__('pkg_resources').run_script('MetaXcan==0.7.5', 'PrediXcan.py')
> ```
> 
> Cheers,
> 
> Steph

Hi Steph,

 You can run the PrediXcan.py added the " #!/usr/bin/env python" in /MetaXcan/software folder.
`cd /MetaXcan/software
./Predixcan.py --help`

good luck,

Weimin

**Comment by hhx037** [comment]
Hi Weimin,

there is no need for #!/usr/bin/env python when running the script from the /MetaXcan/software folder, that's always been working, the issue appears for the installed version of the script, and, of all the scripts, only for PrediXcan.py

Cheers,

Steph
