### ISSUE TITLE
errors at imputation step

### ISSUE THREAD

**Issue by gg-n** [hakyimlab/MetaXcan#107]
Hello,

I am trying to do the imputation step (below), using the sample data provided, and I am getting the following error messages:

%The following imputes a portion of the imput GWAS. 
%The imputation is meant to be split over many executions to improve paralellism
%so you would have to iterate `-chromosome` between [1,22] and `-sub_batch` between [0,_sub_batches],
%ideally in an HPVC environment

python3 $GWAS_TOOLS/gwas_summary_imputation.py \
-by_region_file $DATA/eur_ld.bed.gz \
-gwas_file $OUTPUT/harmonized_gwas/CARDIoGRAM_C4D_CAD_ADDITIVE.txt.gz \
-parquet_genotype $DATA/reference_panel_1000G/chr1.variants.parquet \
-parquet_genotype_metadata $DATA/reference_panel_1000G/variant_metadata.parquet \
-window 100000 \
-parsimony 7 \
-chromosome 1 \
-regularization 0.1 \
-frequency_filter 0.01 \
-sub_batches 10 \
-sub_batch 0 \
--standardise_dosages \
-output $OUTPUT/summary_imputation_1000G/CARDIoGRAM_C4D_CAD_ADDITIVE_chr1_sb0_reg0.1_ff0.01_by_region.txt.gz

----------------------------------------------------------------------------------------

INFO - Beginning process
INFO - Creating context by variant
INFO - Loading study
INFO - Loading variants' parquet file
Traceback (most recent call last):
  File "summary-gwas-imputation/src/gwas_summary_imputation.py", line 97, in <module>
    run(args)
  File "summary-gwas-imputation/src/gwas_summary_imputation.py", line 60, in run
    results = run_by_region(args)
  File "summary-gwas-imputation/src/gwas_summary_imputation.py", line 40, in run_by_region
    context = SummaryImputationUtilities.context_by_region_from_args(args)
  File "/user/PrediXcan/sampledata/summary-gwas-imputation/src/genomic_tools_lib/summary_imputation/Utilities.py", line 229, in context_by_region_from_args
    study = load_study(args)
  File "/user/PrediXcan/sampledata/summary-gwas-imputation/src/genomic_tools_lib/summary_imputation/Utilities.py", line 162, in load_study
    study = Parquet.study_from_parquet(args.parquet_genotype, args.parquet_genotype_metadata, chromosome=args.chromosome)
  File "/user/PrediXcan/sampledata/summary-gwas-imputation/src/genomic_tools_lib/file_formats/Parquet.py", line 218, in study_from_parquet
    _v = pq.ParquetFile(variants)
  File "/home/user/.local/lib/python3.8/site-packages/pyarrow/parquet.py", line 199, in __init__
    self.reader.open(source, use_memory_map=memory_map,
  File "pyarrow/_parquet.pyx", line 1021, in pyarrow._parquet.ParquetReader.open
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
OSError: Couldn't deserialize thrift: TProtocolException: Exceeded size limit

What am I doing wrong? Could someone help me please?

Many thanks for your help.

**Comment by Heroico** [comment]
Hi, 

This is a error in pyarrow library. I suggest using pyarrow version 0.9.0 and downloading the sample data again.

**Comment by gg-n** [comment]
Hi Heroico, 

Thank you so much, it is working now!!

**Comment by Heroico** [comment]
What was it?

**Comment by gg-n** [comment]
It was an error in the pyarrow library as you suggested. Using pyarrow version 0.9.0 has fixed the issue. Many thanks again!
