### ISSUE TITLE
No intersection of snps between GWAS and models.

### ISSUE THREAD

**Issue by KasperFischer** [hakyimlab/MetaXcan#135]
Dear dev team, and MetaXcan experts!

I am running S-Multiscan using the following code

```
python3/SMulTiXcan.py
--models_name_pattern /MetaXcan/data/eqtl/mashr/ 
--models_name_pattern 'mashr_(.*).db' 
--snp_covariance /MetaXcan/data/gtex_v8_expression_mashr_snp_covariance.txt.gz 
--metaxcan_folder /MetaXcan/eqtl/predictions/ 
--metaxcan_filter '(.*).txt' 
--metaxcan_file_name_parse_pattern '(.*).txt' 
--gwas_file  /MetaXcan/imputed_gwas.txt.gz 
--snp_column panel_variant_id 
--effect_allele_column effect_allele  
--zscore_column zscore 
--non_effect_allele_column non_effect_allele 
--keep_non_rsid 
--model_db_snp_key varID 
--cutoff_condition_number 30 
--verbosity 7  
--throw
--output /OUTPUT/Smultixcan.txt

```

When run these commands I get the followin gerror message

```
INFO - Creating context
INFO - Creating MetaXcan results manager
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Adipose_Subcutaneous.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Adipose_Visceral_Omentum.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Adrenal_Gland.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Artery_Aorta.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Artery_Coronary.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Artery_Tibial.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Brain_Amygdala.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Brain_Anterior_cingulate_cortex_BA24.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Brain_Caudate_basal_ganglia.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Brain_Cerebellar_Hemisphere.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Brain_Cerebellum.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Brain_Cortex.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Brain_Frontal_Cortex_BA9.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Brain_Hippocampus.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Brain_Hypothalamus.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Brain_Nucleus_accumbens_basal_ganglia.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Brain_Putamen_basal_ganglia.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Brain_Spinal_cord_cervical_c-1.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Brain_Substantia_nigra.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Breast_Mammary_Tissue.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Cells_Cultured_fibroblasts.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Cells_EBV-transformed_lymphocytes.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Colon_Sigmoid.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Colon_Transverse.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Esophagus_Gastroesophageal_Junction.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Esophagus_Mucosa.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Esophagus_Muscularis.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Heart_Atrial_Appendage.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Heart_Left_Ventricle.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Kidney_Cortex.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Liver.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Lung.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Minor_Salivary_Gland.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Muscle_Skeletal.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Nerve_Tibial.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Ovary.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Pancreas.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Pituitary.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Prostate.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Skin_Not_Sun_Exposed_Suprapubic.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Skin_Sun_Exposed_Lower_leg.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Small_Intestine_Terminal_Ileum.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Spleen.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Stomach.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Testis.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Thyroid.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Uterus.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Vagina.txt.gz
Level 9 - Loading metaxcan /home/MetaXcan/predictions/Whole_Blood.txt.gz
Level 9 - Building data
Level 9 - Processing Adipose_Subcutaneous
Level 9 - Processing Adipose_Visceral_Omentum
Level 9 - Processing Adrenal_Gland
Level 9 - Processing Artery_Aorta
Level 9 - Processing Artery_Coronary
Level 9 - Processing Artery_Tibial
Level 9 - Processing Brain_Amygdala
Level 9 - Processing Brain_Anterior_cingulate_cortex_BA24
Level 9 - Processing Brain_Caudate_basal_ganglia
Level 9 - Processing Brain_Cerebellar_Hemisphere
Level 9 - Processing Brain_Cerebellum
Level 9 - Processing Brain_Cortex
Level 9 - Processing Brain_Frontal_Cortex_BA9
Level 9 - Processing Brain_Hippocampus
Level 9 - Processing Brain_Hypothalamus
Level 9 - Processing Brain_Nucleus_accumbens_basal_ganglia
Level 9 - Processing Brain_Putamen_basal_ganglia
Level 9 - Processing Brain_Spinal_cord_cervical_c-1
Level 9 - Processing Brain_Substantia_nigra
Level 9 - Processing Breast_Mammary_Tissue
Level 9 - Processing Cells_Cultured_fibroblasts
Level 9 - Processing Cells_EBV-transformed_lymphocytes
Level 9 - Processing Colon_Sigmoid
Level 9 - Processing Colon_Transverse
Level 9 - Processing Esophagus_Gastroesophageal_Junction
Level 9 - Processing Esophagus_Mucosa
Level 9 - Processing Esophagus_Muscularis
Level 9 - Processing Heart_Atrial_Appendage
Level 9 - Processing Heart_Left_Ventricle
Level 9 - Processing Kidney_Cortex
Level 9 - Processing Liver
Level 9 - Processing Lung
Level 9 - Processing Minor_Salivary_Gland
Level 9 - Processing Muscle_Skeletal
Level 9 - Processing Nerve_Tibial
Level 9 - Processing Ovary
Level 9 - Processing Pancreas
Level 9 - Processing Pituitary
Level 9 - Processing Prostate
Level 9 - Processing Skin_Not_Sun_Exposed_Suprapubic
Level 9 - Processing Skin_Sun_Exposed_Lower_leg
Level 9 - Processing Small_Intestine_Terminal_Ileum
Level 9 - Processing Spleen
Level 9 - Processing Stomach
Level 9 - Processing Testis
Level 9 - Processing Thyroid
Level 9 - Processing Uterus
Level 9 - Processing Vagina
Level 9 - Processing Whole_Blood
INFO - Loading genes
INFO - Context for snp covariance
INFO - Assessing GWAS-Models SNP intersection
INFO - Processing GWAS command line parameters
INFO - Reading input gwas: /home/MetaXcan/imputed_gwas.txt.gz
/home/MetaXcan/software/metax/gwas/Utilities.py:109: FutureWarning: In a future version of pandas all arguments of read_table except for the argument 'filepath_or_buffer' will be keyword-only
  _l = lambda x: GWAS.load_gwas(x, gwas_format, skip_until_header=args.skip_until_header,
INFO - Processing input gwas
Level 9 - Using declared zscore
Traceback (most recent call last):
  File "/home/MetaXcan/software/SMulTiXcan.py", line 93, in <module>
    run(args)
  File "/home/MetaXcan/software/SMulTiXcan.py", line 22, in run
    context = CrossModelUtilities.context_from_args(args)
  File "/home/MetaXcan/software/metax/cross_model/Utilities.py", line 189, in context_from_args
    raise Exceptions.ReportableException("No intersection of snps between GWAS and models.")
metax.Exceptions.ReportableException: No intersection of snps between GWAS and models.
```

It doesn't make sense that there should be no interasection between GWAS and models, since I have already run S-PrediXcan with the same imputed GWAS succesfully. This leads me to think that there is some coding problem I am making. Can someone please point me in a direction?

Thanks!

**Comment by smellythief** [comment]
I am also having this same issue, despite having successfully run S-PrediXcan on these same GWAS stats. @KasperFischer have you found a remedy for this?!?
