### ISSUE TITLE
ImportError: libathr.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by CuihuaXia** [hakyimlab/MetaXcan#139]
Hello, I have some problems when I run the Predict.py. 

Here is my script:
`Predict.py --model_db_path ~/test_data/predixcan_sample_data/models/gtex_v8_en/en_Whole_Blood.db --bgen_genotypes ~/test_data/predixcan_sample_data/1000G_hg37_bgen/chr22.bgen --bgen_use_rsid --prediction_output Whole_Blood_test_predict.txt --prediction_summary_output Whole_Blood_test_summary.txt --verbosity 9 --throw`

Here is the error:
`INFO - Loading samples
Traceback (most recent call last):
  File "/zs32/home/chxia/Softwares/MetaXcan-master/software/Predict.py", line 272, in <module>
    run(args)
  File "/zs32/home/chxia/Softwares/MetaXcan-master/software/Predict.py", line 160, in run
    samples = load_samples(args)
  File "/zs32/home/chxia/Softwares/MetaXcan-master/software/Predict.py", line 90, in load_samples
    from metax.genotype import BGENGenotype
  File "/zs32/home/chxia/Softwares/MetaXcan-master/software/metax/genotype/BGENGenotype.py", line 1, in <module>
    import bgen_reader
  File "/zs32/home/chxia/anaconda3/envs/gwasimputation/lib/python3.7/site-packages/bgen_reader/__init__.py", line 26, in <module>
    from ._metadata import create_metafile
  File "/zs32/home/chxia/anaconda3/envs/gwasimputation/lib/python3.7/site-packages/bgen_reader/_metadata.py", line 4, in <module>
    from ._bgen import bgen_file
  File "/zs32/home/chxia/anaconda3/envs/gwasimputation/lib/python3.7/site-packages/bgen_reader/_bgen.py", line 3, in <module>
    from ._ffi import ffi, lib
ImportError: libathr.so.1: cannot open shared object file: No such file or directory`

Could you help me solve this problem?

Thanks!

**Comment by Fnyasimi** [comment]
@CuihuaXia  Looks like you environment is missing required packages. Kindly set up your environment using conda as explained [here](https://github.com/hakyimlab/MetaXcan#example-conda-environment-setup)

**Comment by CuihuaXia** [comment]
> 

OK, thanks!

**Comment by CuihuaXia** [comment]
> @CuihuaXia Looks like you environment is missing required packages. Kindly set up your environment using conda as explained [here](https://github.com/hakyimlab/MetaXcan#example-conda-environment-setup)

OK, thanks!

**Comment by Flumenlucidum** [comment]
I had trouble with this issue. After you install with yaml file, make sure you do 'pip install bgen_reader==3.0.3'
