### ISSUE TITLE
how to get  predicted expression level,Tg?

### ISSUE THREAD

**Issue by ymqwa** [hakyimlab/MetaXcan#149]
Hi,
I have GWAS summary data and individual level data in the same cohort, also have DNA methylation prediction models.  I use GWAS summary data to run Predict.py, get the methylation-level association results. Now i want to get the predicted methylation value, just like  predicted expression Tg .  i dont know if it can be got ? and  if can , how to do ?

Thank you,
best mqyang.

**Comment by Fnyasimi** [comment]
have a look at [this](https://github.com/hakyimlab/MetaXcan/wiki/Individual-level-PrediXcan:-introduction,-tutorials-and-manual) for individual level data and [this](https://github.com/hakyimlab/MetaXcan/wiki/S-PrediXcan-Command-Line-Tutorial) for summary stats. 

I hope this helps

**Comment by ymqwa** [comment]
Really appreciate!

but when i run Predict.py, I got the following output:
INFO - Loading samples
INFO - Loading model
INFO - Preparing genotype dosages
INFO - Setting whitelist from available models
INFO - Processing genotypes
INFO - Preparing prediction
INFO - Couldn't import h5py_cache. Anyway, this dependency should be removed. It has been folded into h5py
Level 9 - Processing vcfs
Level 9 - Processing vcf chrall_qc_3.vcf.gz
Traceback (most recent call last):
  File "/Public/xyzhao/data/methylation/metaxcan/MetaXcan-master/software/Predict.py", line 270, in <module>
    run(args)
  File "/Public/xyzhao/data/methylation/metaxcan/MetaXcan-master/software/Predict.py", line 198, in run
    results.update(gene, dosage, weight)
AttributeError: 'NoneType' object has no attribute 'update'

Here is my code:
conda activate MetaXcan
/Public/software/Predict.py \
--model_db_path methylation_r01_FHS.db \
--vcf_genotypes chrall_qc_3.vcf.gz \
--vcf_mode genotyped \
--prediction_output methy_predict.txt \
--prediction_summary_output methy_predict_summary.txt \
--verbosity 9 \
--throw 

i don't know how to fix it. Would you have any thoughts on that?
Looking forward to your reply
best mqyang.

**Comment by DoraCChen** [comment]
Hi, I also had a similar question - 

Since Summary-PrediXcan directly computes the gene-level association results from summary GWAS data, is there any way to derive and output predicted gene expression level Tg? I know that for individual-level PrediXcan it is possible to get Tg output using the Predict.py script, but the association analyses are different between individual and summary-level PrediXcan. How can we extract this information? I looked through the wiki page that was linked for S-PrediXcan but wasn't able to find the relevant information.

**Comment by hakyim** [comment]
Unfortunately, the individual level information cannot be recovered from
the summary statistics. To calculate Tg for a set of individuals, you will
need their genotype data. You can use your own cohort's genotype data and
apply the individual level predixcan prediction software `predict.py` or
use a reference genotype such as 1000G or others.
I hope this helps
Haky
