### ISSUE TITLE
Error when running SMultiXcan.py

### ISSUE THREAD

**Issue by dym22** [hakyimlab/MetaXcan#177]
Hi there,

I successfully ran SPrediXcan on my sumstats file, but am running into the following error when attempting to run SMultiXcan:

(...)
Level 9 - Processing Thyroid
Level 9 - Processing Uterus
Level 9 - Processing Vagina
Level 9 - Processing Whole_Blood
INFO - Loading genes
INFO - Context for snp covariance
INFO - Assessing GWAS-Models SNP intersection
INFO - Processing GWAS command line parameters
INFO - Reading input gwas: /indy/storage3/dym22/CLCLP_38_modified.txt
Traceback (most recent call last):
  File "/indy/storage3/dym22/MetaXcan/software/SMulTiXcan.py", line 93, in <module>
    run(args)
  File "/indy/storage3/dym22/MetaXcan/software/SMulTiXcan.py", line 22, in run
    context = CrossModelUtilities.context_from_args(args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/indy/storage3/dym22/MetaXcan/software/metax/cross_model/Utilities.py", line 186, in context_from_args
    intersection = GWASAndModels.gwas_model_intersection(args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/indy/storage3/dym22/MetaXcan/software/metax/misc/GWASAndModels.py", line 36, in gwas_model_intersection
    gwas= GWASUtilities.load_plain_gwas_from_args(args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/indy/storage3/dym22/MetaXcan/software/metax/gwas/Utilities.py", line 116, in load_plain_gwas_from_args
    files = [_l(x) for x in files]
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/indy/storage3/dym22/MetaXcan/software/metax/gwas/Utilities.py", line 116, in <listcomp>
    files = [_l(x) for x in files]
             ^^^^^
  File "/indy/storage3/dym22/MetaXcan/software/metax/gwas/Utilities.py", line 109, in <lambda>
    _l = lambda x: GWAS.load_gwas(x, gwas_format, skip_until_header=args.skip_until_header,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/indy/storage3/dym22/MetaXcan/software/metax/gwas/GWAS.py", line 103, in load_gwas
    d = pandas.read_table(source, separator)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: read_table() takes 1 positional argument but 2 were given

These are the flags I am using:
python ${PATH_TO_METAXCAN}/SMulTiXcan.py \
--models_folder ${EQTL_DIR} \
--models_name_pattern "mashr_(.*).db" \
--snp_covariance gtex_v8_expression_mashr_snp_smultixcan_covariance.txt.gz \
--metaxcan_folder ${METAXCAN_OUTPUT_DIR} \
--metaxcan_filter "SPrediXcan_(.*).csv" \
--metaxcan_file_name_parse_pattern "SPrediXcan_(.*).csv" \
--gwas_folder /indy/storage3/dym22 \
--gwas_file_pattern "CLCLP_38_modified.txt" \
--snp_column VARIANT \
--effect_allele_column A1 \
--non_effect_allele_column A2 \
--or_column OR \
--pvalue_column P \
--keep_non_rsid \
--model_db_snp_key varID \
--cutoff_condition_number 30 \
--verbosity 7 \
--throw \
--output ${OUTPUT_DIR}/smultixcan_output.txt

I have been unable to find any similar issues reported on the GitHub or in Google Groups. If anyone is able to provide assistance/guidance, it would be much appreciated. Thank you!

**Comment by Hanuphant** [comment]
Implemented a fix that you can use or alternatively, it worked with Python v.3.6.8

https://github.com/hakyimlab/MetaXcan/issues/183#issuecomment-1758451933
