### ISSUE TITLE
ImportError: /lib64/libldap.so.2: undefined symbol: EVP_md2, version OPENSSL_3.0.0

### ISSUE THREAD

**Issue by blairchesnut-at-duke** [hakyimlab/MetaXcan#202]
Got an ImportError while running PrediXcan.py:

INFO - Had to reset logging handlers. Why?
INFO - Running prediction
INFO - Loading samples
Traceback (most recent call last):
  File "/dmpi2/analysis/apps/conda/MetaXcan/software/PrediXcan.py", line 38, in <module>
    run(args)
  File "/dmpi2/analysis/apps/conda/MetaXcan/software/PrediXcan.py", line 14, in run
    prediction_results = Predict.run(args)
  File "/dmpi2/analysis/apps/conda/MetaXcan/software/Predict.py", line 160, in run
    samples = load_samples(args)
  File "/dmpi2/analysis/apps/conda/MetaXcan/software/Predict.py", line 87, in load_samples
    from metax.genotype import CYVCF2Genotype
  File "/dmpi2/analysis/apps/conda/MetaXcan/software/metax/genotype/CYVCF2Genotype.py", line 2, in <module>
    from cyvcf2 import VCF
  File "/dmpi2/analysis/apps/conda/MetaXcan/lib/python3.7/site-packages/cyvcf2/__init__.py", line 1, in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
ImportError: /lib64/libldap.so.2: undefined symbol: EVP_md2, version OPENSSL_3.0.0

We are running on Red Hat EL9 with Python 3.7, pandas==0.25.3, scipy==1.4.1, numpy==1.18.1, bgen_reader==3.0.2, cyvcf2==0.20.0, pyliftover==0.4, statsmodels==0.11.1, h5py==2.10.0, pyarrow==0.11.0

**Comment by blairchesnut-at-duke** [comment]
Installed cyvcf2-0.31.1
