### ISSUE TITLE
ImportError: No module named misc

### ISSUE THREAD

**Issue by jrouhana** [hakyimlab/MetaXcan#84]
Hi,

I'm trying to setup MetaXcan on an HPC. The software versions I'm using are:

Python 2.7.12
Pandas 0.18.1
Scipy 1.2.1
Numpy 1.11.1

After installing the software and making a module out of it, attempting to run MetaXcan.py, or any of the bin files, yields:

>Traceback (most recent call last):
> File "/data/Segre_Lab/modules/software/MetaXcan/bin/MetaXcan.py", line 4, in <module>
>    __import__('pkg_resources').run_script('MetaXcan==0.6.9', 'MetaXcan.py')
> File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 719, in run_script
> File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1511, in run_script
>  File "/data/Segre_Lab/modules/software/MetaXcan/lib/python2.7/site-packages/MetaXcan-0.6.9-py2.7.egg/EGG-INFO/scripts/MetaXcan.py", line 14, in <module>
>  
>  File "/gpfs/fs1/data/Segre_Lab/modules/software/MetaXcan/bin/M03_betas.py", line 4, in <module>
>    __import__('pkg_resources').run_script('MetaXcan==0.6.9', 'M03_betas.py')
>  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 719, in run_script
>  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1511, in run_script
>  File "/data/Segre_Lab/modules/software/MetaXcan/lib/python2.7/site-packages/MetaXcan-0.6.9-py2.7.egg/EGG-INFO/scripts/M03_betas.py", line 23, in <module>
>    
>ImportError: No module named misc`

Any ideas?

**Comment by jrouhana** [comment]
The problem is in `setup.py`, line 19:

>                 packages=['metax','tests','metax.gwas','metax.metaxcan', 'metax.deprecated'],

Should be:

>                 packages=['metax','tests','metax.misc', 'metax.gwas','metax.metaxcan', 'metax.deprecated'], 

This resolves the issue for me.
