### ISSUE TITLE
ImportError: No module named abc with PrediXcan.py script

### ISSUE THREAD

**Issue by hwheeler01** [hakyimlab/MetaXcan#88]
Hi all,
I've been unable to run the PrediXcan.py script with newer versions of Python 2.7. I've tried on

Python 2.7.16 (default, Oct  7 2019, 17:36:04) 
[GCC 8.3.0] on linux2

and

Python 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 7.4.0] on linux2

Here is the error trace:
```
$ PrediXcan.py -h
Traceback (most recent call last):
  File "/usr/local/bin/PrediXcan.py", line 12, in <module>
    from metax.predixcan import PrediXcanAssociation
  File "/usr/local/bin/metax/predixcan/PrediXcanAssociation.py", line 5, in <module>
    import statsmodels.api as sm
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/api.py", line 5, in <module>
    from . import iolib
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/iolib/__init__.py", line 1, in <module>
    from .foreign import StataReader, genfromdta, savetxt
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/iolib/foreign.py", line 14, in <module>
    from statsmodels.compat.python import (lzip, lmap, lrange,
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/compat/__init__.py", line 1, in <module>
    from statsmodels.tools._testing import PytestTester
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/tools/__init__.py", line 1, in <module>
    from .tools import add_constant, categorical
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/tools/tools.py", line 11, in <module>
    from statsmodels.tools.validation import array_like
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/tools/validation/__init__.py", line 1, in <module>
    from .validation import (array_like, bool_like,  dict_like,
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/tools/validation/validation.py", line 1, in <module>
    from collections.abc import Mapping
ImportError: No module named abc
```

Thank you for maintaining a great tool and thanks for any help with this.

**Comment by Heroico** [comment]
Hi Heather,

It looks like an issue with the **statsmodel** package. Can you run a `pip freeze > modules.txt` so that I check the versions?

**Comment by hwheeler01** [comment]
```
$ pip freeze > modules.txt
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
$ cat modules.txt 
asn1crypto==0.24.0
backports.functools-lru-cache==1.5
bitarray==1.1.0
blinker==1.4
bzr==2.8.0.dev1
certifi==2018.8.24
chardet==3.0.4
configobj==5.0.6
configparser==3.5.0b2
cryptography==2.3
cycler==0.10.0
distro==1.3.0
entrypoints==0.3
enum34==1.1.6
funcsigs==1.0.2
h5py==2.10.0
h5py-cache==1.0
httplib2==0.11.3
idna==2.6
ipaddress==1.0.17
keyring==17.1.1
keyrings.alt==3.1.1
kiwisolver==1.1.0
launchpadlib==1.10.6
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
matplotlib==2.2.4
mock==3.0.5
numpy==1.16.5
oauthlib==2.1.0
pandas==0.24.2
patsy==0.5.1
pycrypto==2.6.1
PyGObject==3.32.0
PyJWT==1.7.0
pyOpenSSL==19.0.0
pyparsing==2.4.2
python-dateutil==2.8.1
pytz==2019.3
pyxdg==0.25
requests==2.21.0
scipy==1.2.2
SecretStorage==2.3.1
simplejson==3.16.0
six==1.12.0
SQLAlchemy==1.3.13
statsmodels==0.11.0
subprocess32==3.5.4
urllib3==1.24.1
wadllib==1.3.3
```

**Comment by hwheeler01** [comment]
Thanks, Alvaro, it seems to be running with your Python3 updates. I'll open a new issue if anything else comes up. RIP Python 2.7.

**Comment by Heroico** [comment]
Hi Heather,

I'm glad to hear it got solved. I was scratching my head about this one, the `pip freeze` shows an environment that worked on my end.
